<?php
/** 
 * This file is generated by using `cli.php init` 
 * to initialize application instance configurations. Do not edit manually.
 * 
 * If your application is throwing and exception and you're seeing this message,
 * you probably need to run `cli.php init` from the command line to populate this file.
 * 
 */

throw new \Exception("ApplicationInstanceConfigurations.php is not populated. Please run `cli.php init` to initialize the application database and configurations.");

exit (1);
