<?php

declare(strict_types=1);

namespace Cli\Commands;

use Cli\Attributes\Command;
use Cli\Console\AbstractCommand;
use Cli\Console\Input;
use Cli\Console\Output;
use Dotenv\Dotenv;
use RuntimeException;
use Twig\Environment as TwigEnvironment;
use Twig\Loader\FilesystemLoader as TwigFilesystemLoader;

/**
 * Resets the Docker development environment and clears compiled template caches.
 *
 * This command clears all compiled Twig template files from within the running
 * web container (to avoid host permission issues with container-owned files),
 * then tears down the Docker project and removes named volumes.
 */
#[Command(
    name: 'project-reset',
    description: 'Destroy all DB data, volumes, and generated migrations, then reset the Docker environment.',
    help: 'Stops and removes the Docker project containers, deletes host MariaDB data files in docker/mariadb/data, '
        . 'and clears compiled Twig template caches. This operation is destructive and cannot be undone. '
        . 'All application data is permanently lost. Run `php cli.php init` to reinitialize the database accounts and the schema.',

)]
final class ProjectResetCommand extends AbstractCommand
{
    /**
     * Executes the project-reset workflow.
     */
    public function execute(Input $input, Output $output): int
    {
        $projectRoot = dirname(__DIR__, 2);
        $this->loadEnvironment($projectRoot);

        if ($this->isProjectResetAllowed() === false) {
            $output->warning('Project reset is disabled. Set ALLOW_PROJECT_RESET=true in .env to continue.');
            return 0;
        }

        if ($this->confirm('This will destroy all database data and remove the Docker project containers. Continue?') !== true) {
            $output->info('Reset cancelled.');
            return 0;
        }

        $projectName = getenv('COMPOSE_PROJECT_NAME') ?: 'lampfire';
        $databaseVolumeNames = $this->collectDatabaseVolumeNames($projectRoot, (string) $projectName);

        $output->info('Clearing compiled template caches...');
        $this->clearCompiledTemplates($projectRoot, $output);

        $output->info('Resetting generated migration files...');
        $this->resetMigrationFiles($projectRoot, $output);

        $output->info('Stopping containers and removing volumes...');
        $this->stopComposeProject($projectRoot, $output);
        $this->removeMatchingServiceContainers((string) $projectName, $projectRoot, $output);
        $this->removeNamedVolume((string) $projectName, $projectRoot, $output, $databaseVolumeNames);
        $this->clearHostDatabaseData($projectRoot, $output);
        $this->removeNamedNetwork($projectName, $projectRoot, $output);

        $output->writeln();
        $output->info('Project reset complete.');
        $output->writeln('Run `php cli.php init` to reinitialize the database schema and administrator accounts.');

        return 0;
    }

    /**
     * Returns true when project-reset is allowed by failsafe configuration.
     */
    private function isProjectResetAllowed(): bool
    {
        $value = getenv('ALLOW_PROJECT_RESET');

        if ($value === false) {
            return false;
        }

        return in_array(strtolower(trim((string) $value)), ['1', 'true', 'yes', 'on'], true);
    }

    /**
     * Loads environment values from .env if the file exists.
     *
     * @param string $projectRoot The absolute path to the project root directory.
     */
    private function loadEnvironment(string $projectRoot): void
    {
        $environmentFile = $projectRoot . '/.env';

        if (file_exists($environmentFile) !== true) {
            return;
        }

        $dotenv = Dotenv::createUnsafeImmutable($projectRoot);
        $dotenv->load();
    }

    /**
     * Replaces generated migration files with empty placeholders.
     *
     * The migration files in app/migrations/ are generated by php cli.php init
     * from Twig templates. Resetting the project must restore them to their
     * pre-init state so that init can regenerate them cleanly on the next run.
     *
     * @param string $projectRoot The absolute path to the project root.
     * @param Output $output      The console output.
     */
    private function resetMigrationFiles(string $projectRoot, Output $output): void
    {
        $cliDirectory          = dirname(__DIR__);
        $placeholdersDirectory = $cliDirectory . '/templates/migrations/placeholders';
        $cacheDirectory        = $cliDirectory . '/templates_compiled';
        $migrationsDirectory   = $projectRoot . '/app/migrations';

        $loader = new TwigFilesystemLoader($placeholdersDirectory);
        $twig   = new TwigEnvironment($loader, [
            'cache'       => $cacheDirectory,
            'auto_reload' => true,
        ]);

        $templates = [
            '00001-initial-schema.sql.twig'                   => '00001-initial-schema.sql',
            '00002-create-initial-admin_permissions.sql.twig' => '00002-create-initial-admin_permissions.sql',
        ];

        foreach ($templates as $templateName => $outputFileName) {
            $targetPath = $migrationsDirectory . '/' . $outputFileName;

            if (file_exists($targetPath) !== true) {
                continue;
            }

            $sql = $twig->render($templateName, []);

            if (file_put_contents($targetPath, $sql) === false) {
                $output->warning(sprintf('Could not reset migration file: %s', $outputFileName));
                continue;
            }

            $output->writeln(sprintf('  Reset: %s', $outputFileName));
        }
    }

    /**
     * Clears the compiled Twig template caches.
     *
     * Deletes cached files from within the running web container to avoid host
     * permission issues caused by files written by the container's web user.
     * Falls back to direct PHP deletion when the container is not running.
     *
     * @param string $projectRoot The absolute path to the project root.
     * @param Output $output      The console output.
     */
    private function clearCompiledTemplates(string $projectRoot, Output $output): void
    {
        $containerId = $this->getRunningServiceContainerId($projectRoot, 'lampfire-web');

        if ($containerId === '') {
            $output->warning('Web container is not running. Attempting direct deletion of template caches.');
            $this->clearDirectory($projectRoot . '/app/templates_compiled', $output);
            $this->clearDirectory($projectRoot . '/cli/templates_compiled', $output);
            return;
        }

        $containerCommand = 'docker exec ' . escapeshellarg($containerId) . ' sh -c '
            . escapeshellarg(
                'find /var/www/app/app/templates_compiled -mindepth 1 -delete 2>/dev/null;'
                . ' find /var/www/app/cli/templates_compiled -mindepth 1 -delete 2>/dev/null;'
                . ' true'
            );

        $exitCode = $this->runShellCommand($containerCommand, $projectRoot, $output);

        if ($exitCode !== 0) {
            $output->warning('Web container is not running. Attempting direct deletion of template caches.');
            $this->clearDirectory($projectRoot . '/app/templates_compiled', $output);
            $this->clearDirectory($projectRoot . '/cli/templates_compiled', $output);
            return;
        }

        $output->writeln('  Cleared: app/templates_compiled');
        $output->writeln('  Cleared: cli/templates_compiled');
    }

    /**
     * Runs a shell command in the given working directory and streams its output
     * to the console.
     *
     * Stderr is merged into stdout so that Docker progress output is visible.
     *
     * @param string $command The shell command to execute.
     * @param string $cwd     The working directory for the command.
     * @param Output $output  The console output.
     * @return int The process exit code.
     * @throws RuntimeException When the process cannot be started.
     */
    private function runShellCommand(string $command, string $cwd, Output $output): int
    {
        $descriptors = [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['redirect', 1],
        ];

        $process = proc_open($command, $descriptors, $pipes, $cwd);

        if (is_resource($process) !== true) {
            throw new RuntimeException(sprintf('Failed to start process: %s', $command));
        }

        fclose($pipes[0]);

        while (feof($pipes[1]) !== true) {
            $line = fgets($pipes[1]);
            if (is_string($line) && trim($line) !== '') {
                $output->writeln(trim($line));
            }
        }

        fclose($pipes[1]);

        return proc_close($process);
    }

    /**
     * Stops the compose project when Docker Compose is available.
     */
    private function stopComposeProject(string $projectRoot, Output $output): void
    {
        $compose = $this->resolveComposeCommand($projectRoot);

        if ($compose === null) {
            return;
        }

        $exitCode = $this->runShellCommand(
            sprintf('%s down --volumes --remove-orphans', $compose),
            $projectRoot,
            $output,
        );

        if ($exitCode !== 0) {
            $output->warning('Compose down returned a non-zero status. Continuing with force-removal of containers.');
        }
    }

    /**
     * Removes service containers whose names match the application service suffixes.
     */
    private function removeMatchingServiceContainers(string $projectName, string $projectRoot, Output $output): void
    {
        $idsByProject = trim($this->captureShellOutput(
            sprintf(
                'docker ps -aq --filter %s',
                escapeshellarg('label=com.docker.compose.project=' . $projectName)
            ),
            $projectRoot,
        ));

        $idsByName = trim($this->captureShellOutput(
            'docker ps -aq --filter ' . escapeshellarg('name=lampfire-web')
            . ' --filter ' . escapeshellarg('name=lampfire-db')
            . ' --filter ' . escapeshellarg('name=lampfire-cli'),
            $projectRoot,
        ));

        $containerIds = [];

        foreach ([$idsByProject, $idsByName] as $idOutput) {
            if ($idOutput === '') {
                continue;
            }

            $ids = preg_split('/\s+/', $idOutput);

            if (is_array($ids) !== true) {
                continue;
            }

            foreach ($ids as $id) {
                if ($id !== '') {
                    $containerIds[$id] = $id;
                }
            }
        }

        if (count($containerIds) === 0) {
            return;
        }

        $exitCode = $this->runShellCommand(
            'docker rm -f ' . implode(' ', array_map('escapeshellarg', array_values($containerIds))),
            $projectRoot,
            $output,
        );

        if ($exitCode !== 0) {
            $output->warning('One or more containers could not be removed during forced cleanup.');
        }
    }

    /**
     * Returns the compose command when available, or null when absent.
     */
    private function resolveComposeCommand(string $projectRoot): ?string
    {
        if ($this->commandSucceeds('docker compose version >/dev/null 2>&1', $projectRoot)) {
            return 'docker compose';
        }

        return null;
    }

    /**
     * Returns true when a shell command exits successfully.
     */
    private function commandSucceeds(string $command, string $projectRoot): bool
    {
        $descriptors = [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ];

        $process = proc_open($command, $descriptors, $pipes, $projectRoot);

        if (is_resource($process) !== true) {
            return false;
        }

        fclose($pipes[0]);
        stream_get_contents($pipes[1]);
        stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);

        return proc_close($process) === 0;
    }

    /**
     * Captures stdout from a shell command.
     */
    private function captureShellOutput(string $command, string $cwd): string
    {
        $descriptors = [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ];

        $process = proc_open($command, $descriptors, $pipes, $cwd);

        if (is_resource($process) !== true) {
            throw new RuntimeException(sprintf('Failed to start process: %s', $command));
        }

        fclose($pipes[0]);
        $stdout = stream_get_contents($pipes[1]);
        stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        proc_close($process);

        return is_string($stdout) ? $stdout : '';
    }

    /**
     * Returns the ID of a running service container, or an empty string when absent.
     */
    private function getRunningServiceContainerId(string $projectRoot, string $nameFragment): string
    {
        $output = trim($this->captureShellOutput(
            sprintf('docker ps -q --filter %s', escapeshellarg('name=' . $nameFragment)),
            $projectRoot,
        ));

        if ($output === '') {
            return '';
        }

        $lines = preg_split('/\s+/', $output);

        return is_array($lines) && isset($lines[0]) ? (string) $lines[0] : '';
    }

    /**
     * Collects all database volume names that may belong to the project.
     *
     * This includes the conventional Compose volume name, any volume discovered
     * from lampfire-db container mounts, and volumes with matching Compose labels.
     *
     * @param string $projectRoot The absolute path to the project root.
     * @param string $projectName The Compose project name.
     * @return array<int, string> A de-duplicated list of candidate volume names.
     */
    private function collectDatabaseVolumeNames(string $projectRoot, string $projectName): array
    {
        $names = [$projectName . '_db_data'];

        $containerIdsRaw = trim($this->captureShellOutput(
            sprintf('docker ps -aq --filter %s', escapeshellarg('name=lampfire-db')),
            $projectRoot,
        ));

        if ($containerIdsRaw !== '') {
            $containerIds = preg_split('/\s+/', $containerIdsRaw);

            if (is_array($containerIds) === true) {
                foreach ($containerIds as $containerId) {
                    if ($containerId === '') {
                        continue;
                    }

                    $mountedVolumeNamesRaw = trim($this->captureShellOutput(
                        sprintf(
                            "docker inspect --format='{{range .Mounts}}{{if eq .Type \"volume\"}}{{println .Name}}{{end}}{{end}}' %s",
                            escapeshellarg($containerId)
                        ),
                        $projectRoot,
                    ));

                    if ($mountedVolumeNamesRaw === '') {
                        continue;
                    }

                    $mountedVolumeNames = preg_split('/\s+/', $mountedVolumeNamesRaw);

                    if (is_array($mountedVolumeNames) !== true) {
                        continue;
                    }

                    foreach ($mountedVolumeNames as $mountedVolumeName) {
                        if ($mountedVolumeName !== '') {
                            $names[] = $mountedVolumeName;
                        }
                    }
                }
            }
        }

        $labeledVolumeNamesRaw = trim($this->captureShellOutput(
            sprintf(
                'docker volume ls -q --filter %s --filter %s',
                escapeshellarg('label=com.docker.compose.project=' . $projectName),
                escapeshellarg('label=com.docker.compose.volume=db_data')
            ),
            $projectRoot,
        ));

        if ($labeledVolumeNamesRaw !== '') {
            $labeledVolumeNames = preg_split('/\s+/', $labeledVolumeNamesRaw);

            if (is_array($labeledVolumeNames) === true) {
                foreach ($labeledVolumeNames as $labeledVolumeName) {
                    if ($labeledVolumeName !== '') {
                        $names[] = $labeledVolumeName;
                    }
                }
            }
        }

        $names = array_values(array_unique($names));

        return $names;
    }

    /**
     * Removes the named Docker volume for this project.
     *
     * The volume name is derived from the Compose project name following Docker's
     * default naming convention: {project}_{volume}. Failures are suppressed because
     * the volume may not exist on a fresh checkout or after a prior clean reset.
     *
     * @param string $projectName The Compose project name.
     * @param string $projectRoot The absolute path to the project root.
     * @param Output $output      The console output.
     */
    private function removeNamedVolume(string $projectName, string $projectRoot, Output $output, array $databaseVolumeNames): void
    {
        $candidateVolumeNames = array_values(array_unique(array_merge($databaseVolumeNames, [$projectName . '_db_data'])));

        if (count($candidateVolumeNames) === 0) {
            return;
        }

        $this->runShellCommand(
            'docker volume rm ' . implode(' ', array_map('escapeshellarg', $candidateVolumeNames)) . ' 2>/dev/null || true',
            $projectRoot,
            $output,
        );
    }

    /**
     * Removes the named Docker network for this project.
     *
     * The network name is derived from the Compose project name following the naming
     * convention defined in docker-compose.yml: {project}_network. Failures are suppressed
     * because the network may not exist on a fresh checkout or after a prior clean reset.
     *
     * @param string $projectName The Compose project name.
     * @param string $projectRoot The absolute path to the project root.
     * @param Output $output      The console output.
     */
    private function removeNamedNetwork(string $projectName, string $projectRoot, Output $output): void
    {
        $networkName = $projectName . '_network';
        $this->runShellCommand(
            sprintf('docker network rm %s 2>/dev/null || true', escapeshellarg($networkName)),
            $projectRoot,
            $output,
        );
    }

    /**
     * Deletes MariaDB data files stored on the host filesystem.
     *
     * This path is bind-mounted into the db container as /var/lib/mysql.
     *
     * @param string $projectRoot The absolute path to the project root.
     * @param Output $output      The console output.
     */
    private function clearHostDatabaseData(string $projectRoot, Output $output): void
    {
        $databaseDataDirectory = $projectRoot . '/docker/mariadb/data';

        if (is_dir($databaseDataDirectory) !== true) {
            return;
        }

        // The data directory always contains files owned by the MariaDB container
        // process, which cannot be removed from the host without elevated privileges.
        // A one-off root container is used to guarantee complete removal.
        $this->forceClearDirectoryWithDocker($databaseDataDirectory, $projectRoot, $output);
        $output->writeln(sprintf('  Cleared: %s', $databaseDataDirectory));

        $gitKeepPath = $databaseDataDirectory . '/.gitkeep';

        if (file_exists($gitKeepPath) !== true) {
            $created = @file_put_contents($gitKeepPath, '');

            if ($created === false) {
                $output->warning('Could not recreate docker/mariadb/data/.gitkeep after clearing host database data.');
            }
        }
    }

    /**
     * Clears a host directory using a one-off MariaDB container.
     *
     * This fallback handles files that are not removable by the current host user.
     *
     * @param string $directory   The absolute host directory path.
     * @param string $projectRoot The absolute project root path.
     * @param Output $output      The console output.
     */
    private function forceClearDirectoryWithDocker(string $directory, string $projectRoot, Output $output): void
    {
        $quotedDirectory = escapeshellarg($directory);

        $command = sprintf(
            'docker run --rm --user root -v %s:/var/lib/mysql mariadb:11 sh -c %s',
            $quotedDirectory,
            escapeshellarg('rm -rf /var/lib/mysql/* /var/lib/mysql/.[!.]* /var/lib/mysql/..?* 2>/dev/null || true; chmod -R a+rwX /var/lib/mysql 2>/dev/null || true')
        );

        $exitCode = $this->runShellCommand($command, $projectRoot, $output);

        if ($exitCode !== 0) {
            $output->warning('Docker-assisted cleanup could not fully clear docker/mariadb/data.');
        }
    }

    /**
     * Deletes all files and subdirectories inside a directory, preserving
     * the directory itself.
     *
     * Failures are reported as warnings rather than fatal errors because some
     * files may be owned by the container's web user and cannot be removed
     * from the host without elevated privileges.
     *
     * @param string $directory The directory to clear.
     * @param Output $output    The console output.
     */
    private function clearDirectory(string $directory, Output $output): bool
    {
        if (is_dir($directory) !== true) {
            return true;
        }

        try {
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator(
                    $directory,
                    \FilesystemIterator::SKIP_DOTS
                ),
                \RecursiveIteratorIterator::CHILD_FIRST,
                \RecursiveIteratorIterator::CATCH_GET_CHILD
            );
        } catch (\Throwable $throwable) {
            $output->warning(sprintf(
                'Could not traverse %s: %s',
                $directory,
                $throwable->getMessage()
            ));

            return false;
        }

        $failed = false;

        foreach ($iterator as $fileInfo) {
            $path   = $fileInfo->getRealPath();
            $result = $fileInfo->isDir() ? @rmdir($path) : @unlink($path);

            if ($result === false) {
                $failed = true;
            }
        }

        if ($failed) {
            $output->warning(sprintf(
                'Could not fully clear %s. Some files may be owned by the container user.',
                $directory
            ));

            return false;
        }

        $output->writeln(sprintf('  Cleared: %s', $directory));

        return true;
    }
}
